name: Deploy Databricks Bundle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [project1]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install databricks-cli pyyaml

    - name: Create Databricks Bundle
      run: |
        cd ${{ matrix.project }}
        python create_bundle.py

    - name: Upload Databricks Bundle
      run: |
        databricks fs cp -r ${{ matrix.project }}/databricks-dlt_1.0.0 dbfs:/FileStore/databricks-dlt_1.0.0

    - name: Deploy DLT Pipeline
      run: |
        databricks sql --path dbfs:/FileStore/databricks-dlt_1.0.0/notebooks/transform1.sql
        databricks sql --path dbfs:/FileStore/databricks-dlt_1.0.0/notebooks/transform2.sql
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
